obj-$(CONFIG_IRIS_IRMA_SIX_MEM_HELPER) += irma-six-mem-helper.o irma-six-dma-mem-helper.o
obj-$(CONFIG_IRIS_IRMA_SIX_HARDWARE_DISCOVERY) += irma-six-discovery.o
obj-$(CONFIG_VIDEO_IRIS_GEN6_APTINA_MT9V022_CAPTURE) += irma-six-aptinaclock.o
obj-$(CONFIG_IRIS_IRMA_SIX_HADC) += hadc.o
obj-$(CONFIG_IRIS_IRMA_SIX_TMU) += tmu.o
