obj-$(CONFIG_IRIS_GEN6_MEM_HELPER) += gen6-memory.o
obj-$(CONFIG_IRIS_IRMA_SIX_SHARC) += irma-six-sharc.o
obj-$(CONFIG_IRIS_CACHE_CONTROL) += cache-control.o
obj-$(CONFIG_IRIS_IRMA_SIX_HADC) += hadc.o
obj-$(CONFIG_IRIS_IRMA_SIX_TMU) += tmu.o
obj-$(CONFIG_IRIS_IRMA_SIX_HWREVISION) += hwrev.o
